# Generated by Django 6.0.1 on 2026-01-30 08:41

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('miapp01', '0002_tarea'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE Tareas RENAME TO miapp01_tarea;",
            reverse_sql="ALTER TABLE miapp01_tarea RENAME TO Tareas;"
        ),
    ]
    